name: Java CI Build and Debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: ADDED FOR DEBUGGING - List all files in the project
      - name: List files in the repository
        run: ls -R

      # Step 3: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 4: Compile the Java source code (This will likely fail again)
      - name: Compile Java application
        run: |
          mkdir -p out
          # This command is what we need to fix.
          # The debugging step above will tell us the correct path to use.
          javac -d out registration_login/Login.java registration_login/Registration_Login.java
